### ISSUE TITLE
Can't register an account

### ISSUE THREAD

**Issue by Quentendo** [PintoIM/Pinto#2]
Gave me this error when signing in
![Screenshot_39](https://user-images.githubusercontent.com/112523787/235553704-4c459e6d-cb6a-49c5-87bc-830c8a03e671.png)

Heres what the console says:
Performing first time initialization...
[General] Loading saved login information...
[Networking] Registering in as Quentin at 127.0.0.1:2407...
[Networking] Disconnecting...
[Networking] Unable to connect to 127.0.0.1:2407: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:2407
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PintoNS.Networking.NetworkClient.<Connect>d__13.MoveNext() in D:\dev\C#\Pinto\Pinto\Networking\NetworkClient.cs:line 42
[General] Loading saved login information...
[Networking] Registering in as Quentin at 127.0.0.1:2407...
[Networking] Disconnecting...
[Networking] Unable to connect to 127.0.0.1:2407: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:2407
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1
.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PintoNS.Networking.NetworkClient.<Connect>d__13.MoveNext() in D:\dev\C#\Pinto\Pinto\Networking\NetworkClient.cs:line 42

**Comment by vlOd2** [comment]
You forgot to set the server on register section. Either set it to the official one or any other third party one
