### ISSUE TITLE
Pinto gives error when you try to add friend after getting kicked or disconnected

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#25]
System.NullReferenceException: Object reference not set to an instance of an object.
   at PintoNS.Forms.AddContactForm.btnAdd_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by vlOd2** [comment]
Not enough details, please elaborate

**Comment by DexrnZacAttack** [comment]
If you try to accept a friend request after getting kicked from the server or you get disconnected, it will give you a fatal error.

**Comment by vlOd2** [comment]
Please recreate with the new issue template
