### ISSUE TITLE
Crash when adding a contact in a specific condition

### ISSUE THREAD

**Issue by vlOd2** [PintoIM/Pinto#27]
## Describe the bug
Pinto! crashes when adding a contact in a specific condition

## To Reproduce
Needs more investigation

## Additional context
System.NullReferenceException: Object reference not set to an instance of an object.
   at PintoNS.Forms.AddContactForm.btnAdd_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by vlOd2** [comment]
Fixed
