### ISSUE TITLE
Pinto crashes when trying to read a nonexistent extensions folder

### ISSUE THREAD

**Issue by ghost** [PintoIM/Pinto#46]
## Describe the bug
When I run Pinto, it immediately crashes because the extensions folder does not exist.

## To Reproduce
1. Somehow make the "extensions" folder not exist
2. Run Pinto

## Expected behavior
It will create the folder by itself and not crash.

**Comment by vlOd2** [comment]
Please put the full log otherwise I will mark this issue as closed

**Comment by ghost** [comment]
Error log:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Roaming\Pinto!\extensions'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at PintoNS.Program.LoadExtensions() in D:\dev\C#\Pinto\Pinto\Program.cs:line 119
   at PintoNS.Program.Main() in D:\dev\C#\Pinto\Pinto\Program.cs:line 102
   ```

**Comment by unnaturalistic** [comment]
happened to me as well
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Roaming\Pinto!\extensions'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at PintoNS.Program.LoadExtensions() in D:\dev\C#\Pinto\Pinto\Program.cs:line 119
   at PintoNS.Program.Main() in D:\dev\C#\Pinto\Pinto\Program.cs:line 102
```

**Comment by vlOd2** [comment]
Fixed
