### ISSUE TITLE
Pinto! Fatal Error on launch - 15" 2010 Macbook Pro - Windows 7 SP1 7601

### ISSUE THREAD

**Issue by illirnate** [PintoIM/Pinto#59]
## Describe the bug
Launching Pinto! b1.1 crashes immediately running on a 15" 2010 Macbook Pro (Running Windows 7)

## To Reproduce
Don't think this is reproducible but,
Just Launching the program crashes.

## Expected behavior
I expected a Pinto! login, but got a crash.

## Screenshots
[https://ibb.co/GpK5Kdp](url)

## Desktop (please complete the following information):
- OS: Windows 7 Ultimate SP1 7601
- Pinto! Version: Pinto! b1.1

## Additional context
_I've installed .NET Framework 4.0,_ so I don't really know what caused the crash.

Crash Report:

**System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
File name: 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at PintoNS.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].**

**Comment by vlOd2** [comment]
Is this Windows 7 x86 or x64?
Also you don't need to install .NET 4.0, as that isn't the latest version of .NET for your OS. That's what you need, and for Windows 7 that is [.NET 4.7.2](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472)

Please install .NET 4.7.2 and then provide your architecture here (x86 or x64)

**Comment by vlOd2** [comment]
Closing due to lack of activity
